### ISSUE TITLE
Weird issue with strings

### ISSUE THREAD

**Issue by jfmcbrayer** [cxxxr/cl-toml#2]
This is probably human error on my part, as I'm a CL newbie, but I am having issues with string values read from a TOML file being unacceptable to various functions in widely used libraries. For example, I load a hostname for a server to bind to and pass it to usocket:socket-server, and get a type-case error saying something like "127.0.0.1" is not a SIMPLE-STRING. Similar results if I read a path to a cert and try to pass it to cl+ssl:make-ssl-server-stream.

Everything I try in the repl says that they are strings, and that they are EQUAL to working strings I have entered by hand. They work properly if I encode and decode them through babel: (babel:octets-to-string (babel:string-to-octets bad-string)).

I'm sure I'm doing something wrong here, but I can't see what.

**Comment by cxxxr** [comment]
Thank you for your report.
Changed to return simple-string.
Try it in the master branch.

**Comment by jfmcbrayer** [comment]
Yes, I cloned your repo and checked out the master branch in a folder in my asdf registry path, and loaded it into my SLIME session with ql:quickload. Then I removed my workaround from my own code, and loaded my own code with ql:quickload, and ran it. It works, so I believe that this change resolves the issue.
